/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Statistics;

import gbibilio.MenuLivres.*;
import gbibilio.MenuAdherant.MenuEtudiant;
import gbibilio.MenuPret.MenuPret;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import login.Login;
/*import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;*/

/**
 *
 * @author mehdi
 */
public class Statistic extends javax.swing.JFrame {

    Connection con = null;
    Connection con1 = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;
    DefaultTableModel tb1model;
    String auteur;
    String isbn;
    String titre;
    String nbpages;
    String edition;
    String id;
    String etat = "0";

    /**
     * Creates new form Menu
     */
    public Statistic() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Menu1 = new javax.swing.JPanel();
        MenuL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Livre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Adherant = new javax.swing.JLabel();
        MenuAdhe = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pret = new javax.swing.JLabel();
        menupret = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        livres = new javax.swing.JButton();
        adherant = new javax.swing.JButton();
        emprintes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu1.setBackground(new java.awt.Color(102, 102, 255));
        Menu1.setLayout(null);

        MenuL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuL.setForeground(new java.awt.Color(255, 255, 255));
        MenuL.setText("Gestion Livre");
        Menu1.add(MenuL);
        MenuL.setBounds(40, 160, 128, 30);
        Menu1.add(jSeparator1);
        jSeparator1.setBounds(0, 190, 190, 10);

        Livre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livres (1).png"))); // NOI18N
        Livre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LivreMouseClicked(evt);
            }
        });
        Menu1.add(Livre);
        Livre.setBounds(50, 40, 90, 106);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestion Statictics");
        Menu1.add(jLabel4);
        jLabel4.setBounds(28, 639, 128, 30);
        Menu1.add(jSeparator2);
        jSeparator2.setBounds(-2, 343, 190, 10);

        Adherant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student (1).png"))); // NOI18N
        Adherant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdherantMouseClicked(evt);
            }
        });
        Menu1.add(Adherant);
        Adherant.setBounds(40, 200, 120, 110);

        MenuAdhe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuAdhe.setForeground(new java.awt.Color(255, 255, 255));
        MenuAdhe.setText("Gestion Adherant");
        MenuAdhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdheMouseClicked(evt);
            }
        });
        Menu1.add(MenuAdhe);
        MenuAdhe.setBounds(30, 310, 128, 30);
        Menu1.add(jSeparator3);
        jSeparator3.setBounds(0, 508, 190, 10);

        pret.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knowledge (1).png"))); // NOI18N
        pret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pretMouseClicked(evt);
            }
        });
        Menu1.add(pret);
        pret.setBounds(31, 366, 120, 90);

        menupret.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menupret.setForeground(new java.awt.Color(255, 255, 255));
        menupret.setText("Gestion des prêts");
        menupret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menupretMouseClicked(evt);
            }
        });
        Menu1.add(menupret);
        menupret.setBounds(32, 471, 128, 30);
        Menu1.add(jSeparator4);
        jSeparator4.setBounds(0, 676, 190, 10);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        Menu1.add(jLabel10);
        jLabel10.setBounds(30, 690, 130, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Se deconnecter");
        Menu1.add(jLabel9);
        jLabel9.setBounds(33, 740, 128, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph-bar (2).png"))); // NOI18N
        Menu1.add(jLabel13);
        jLabel13.setBounds(40, 530, 130, 110);

        Menu2.setBackground(new java.awt.Color(255, 255, 255));
        Menu2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel12.setText("Les Statistiques de gestion ");
        Menu2.add(jLabel12);
        jLabel12.setBounds(269, 62, 643, 51);

        livres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livres (1).png"))); // NOI18N
        livres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                livresMouseClicked(evt);
            }
        });
        livres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livresActionPerformed(evt);
            }
        });
        Menu2.add(livres);
        livres.setBounds(740, 360, 180, 130);

        adherant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student (1).png"))); // NOI18N
        adherant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adherantMouseClicked(evt);
            }
        });
        adherant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adherantActionPerformed(evt);
            }
        });
        Menu2.add(adherant);
        adherant.setBounds(90, 360, 160, 140);

        emprintes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knowledge (1).png"))); // NOI18N
        emprintes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emprintesMouseClicked(evt);
            }
        });
        emprintes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprintesActionPerformed(evt);
            }
        });
        Menu2.add(emprintes);
        emprintes.setBounds(390, 360, 230, 140);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Stats Livres");
        Menu2.add(jLabel1);
        jLabel1.setBounds(770, 510, 150, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Stats Students");
        Menu2.add(jLabel2);
        jLabel2.setBounds(100, 520, 150, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Stats Préts");
        Menu2.add(jLabel3);
        jLabel3.setBounds(450, 520, 150, 22);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel6.setText("Cette section représente un résumé récaputilatif sur l'ensemble des informations sur tous élements  Adhérant , livres et gestion des préts ");
        Menu2.add(jLabel6);
        jLabel6.setBounds(110, 110, 880, 60);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel7.setText(" Merci de choisir le stats que vous voulez consulter  : ");
        Menu2.add(jLabel7);
        jLabel7.setBounds(300, 160, 580, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\El Mehdi Haddadi\\Downloads\\curve-arrow (1).png")); // NOI18N
        Menu2.add(jLabel5);
        jLabel5.setBounds(110, 210, 160, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAdheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdheMouseClicked
        MenuEtudiant m = new MenuEtudiant();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuAdheMouseClicked

    private void AdherantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdherantMouseClicked

    }//GEN-LAST:event_AdherantMouseClicked

    private void LivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LivreMouseClicked
        MenuLivres m = new MenuLivres();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LivreMouseClicked

    private void menupretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menupretMouseClicked
        MenuPret m = new MenuPret();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_menupretMouseClicked

    private void pretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretMouseClicked
        MenuPret m = new MenuPret();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pretMouseClicked

    private void livresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_livresActionPerformed

    private void livresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livresMouseClicked
     /*   try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");

            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\El Mehdi Haddadi\\Documents\\NetBeansProjects\\Gbiblio\\src\\Statistics\\inv2.jrxml");
            String query = "select COUNT(*) as nbexemplaires ,livre.ISBN,livre.TITRE,livre.EDITION,livre.NBPAGES,auteur.NOM from exemplaire , livre , auteur where exemplaire.ISBN=livre.ISBN and livre.CODEAUTEUR=auteur.CODEAUTEUR GROUP BY livre.ISBN;";

            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(query);

            jdesign.setQuery(newquery);

            JasperReport js = JasperCompileManager.compileReport(jdesign);

            JasperPrint jp = JasperFillManager.fillReport(js, null, con);
            JasperViewer.viewReport(jp);

        } catch (SQLException ex) {
            Logger.getLogger(Statistic.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Statistic.class.getName()).log(Level.SEVERE, null, ex);
        }*/


    }//GEN-LAST:event_livresMouseClicked

    private void adherantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adherantMouseClicked
      /*  try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");

            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\El Mehdi Haddadi\\Documents\\NetBeansProjects\\Gbiblio\\src\\Statistics\\inventory.jrxml");
            String query = "select adherant.codeadherant,adherant.NOM,adherant.PRENOM,adherant.ADRESSE,adherant.nbexemplaires from adherant;";

            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(query);

            jdesign.setQuery(newquery);

            JasperReport js = JasperCompileManager.compileReport(jdesign);

            JasperPrint jp = JasperFillManager.fillReport(js, null, con);
            JasperViewer.viewReport(jp);

        } catch (SQLException ex) {
            Logger.getLogger(Statistic.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Statistic.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_adherantMouseClicked

    private void adherantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adherantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adherantActionPerformed

    private void emprintesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprintesMouseClicked
       /* try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");

            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\El Mehdi Haddadi\\Documents\\NetBeansProjects\\Gbiblio\\src\\Statistics\\inv4.jrxml");
            String query = "select adherant.NOM,adherant.PRENOM,emprunter.DATEEMPRUNTE,emprunter.DATERETOUR,livre.TITRE from emprunter INNER join adherant on adherant.CodeAdherant=emprunter.CodeAdherant INNER join exemplaire on exemplaire.CodeExemplaire=emprunter.CODEEXEMPLAIRE INNER join livre on livre.ISBN = exemplaire.ISBN;";

            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(query);

            jdesign.setQuery(newquery);

            JasperReport js = JasperCompileManager.compileReport(jdesign);

            JasperPrint jp = JasperFillManager.fillReport(js, null, con);
            JasperViewer.viewReport(jp);

        } catch (SQLException ex) {
            Logger.getLogger(Statistic.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Statistic.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_emprintesMouseClicked

    private void emprintesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprintesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emprintesActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Login m = new Login();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adherant;
    private javax.swing.JLabel Livre;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JLabel MenuAdhe;
    private javax.swing.JLabel MenuL;
    private javax.swing.JButton adherant;
    private javax.swing.JButton emprintes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton livres;
    private javax.swing.JLabel menupret;
    private javax.swing.JLabel pret;
    // End of variables declaration//GEN-END:variables
}
