/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbibilio.MenuAdherant;

import Statistics.Statistic;
import gbibilio.MenuLivres.MenuLivres;
import gbibilio.MenuPret.MenuPret;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import login.Login;

/**
 *
 * @author mehdi
 */
public class MenuEtudiant extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    DefaultTableModel tb1model;
    String auteur;
    String nom;
    String prenom;
    String adresse;
    String nbExemplaires;
    String id;
    String code;
    String isbn;

    /**
     * Creates new form Menu
     */
    public MenuEtudiant() {
        initComponents();
        showdate();
        showTime();
        this.setLocationRelativeTo(null);

    }

    void showdate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyy");
        datelabel1.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() { // pendant 0 secande fait moi une action qui s'appele 'ActionListener'
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timelabel1.setText(s.format(d));

            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu1 = new javax.swing.JPanel();
        pret = new javax.swing.JLabel();
        MenuL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Livre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Adherant = new javax.swing.JLabel();
        MenuAdh = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        menuppret = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        Chercher = new javax.swing.JButton();
        filteTXT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BEmprinter = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Actualiser = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        timelabel1 = new javax.swing.JLabel();
        datelabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu1.setBackground(new java.awt.Color(102, 102, 255));
        Menu1.setLayout(null);

        pret.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knowledge (1).png"))); // NOI18N
        pret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pretMouseClicked(evt);
            }
        });
        Menu1.add(pret);
        pret.setBounds(37, 363, 120, 130);

        MenuL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuL.setForeground(new java.awt.Color(255, 255, 255));
        MenuL.setText("Gestion Livre");
        MenuL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLMouseClicked(evt);
            }
        });
        Menu1.add(MenuL);
        MenuL.setBounds(40, 140, 128, 30);
        Menu1.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 190, 10);

        Livre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livres (1).png"))); // NOI18N
        Livre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LivreMouseClicked(evt);
            }
        });
        Menu1.add(Livre);
        Livre.setBounds(40, 20, 120, 106);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestion Statictics");
        Menu1.add(jLabel4);
        jLabel4.setBounds(30, 650, 128, 30);
        Menu1.add(jSeparator2);
        jSeparator2.setBounds(0, 350, 190, 10);

        Adherant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student (1).png"))); // NOI18N
        Menu1.add(Adherant);
        Adherant.setBounds(40, 200, 120, 110);

        MenuAdh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuAdh.setForeground(new java.awt.Color(255, 255, 255));
        MenuAdh.setText("Gestion Adherant");
        MenuAdh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdhMouseClicked(evt);
            }
        });
        Menu1.add(MenuAdh);
        MenuAdh.setBounds(30, 320, 128, 30);
        Menu1.add(jSeparator3);
        jSeparator3.setBounds(0, 520, 190, 10);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph-bar (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        Menu1.add(jLabel7);
        jLabel7.setBounds(31, 526, 130, 120);

        menuppret.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuppret.setForeground(new java.awt.Color(255, 255, 255));
        menuppret.setText("Gestion des prêts");
        menuppret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuppretMouseClicked(evt);
            }
        });
        Menu1.add(menuppret);
        menuppret.setBounds(30, 490, 128, 30);
        Menu1.add(jSeparator4);
        jSeparator4.setBounds(0, 680, 190, 10);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        Menu1.add(jLabel10);
        jLabel10.setBounds(31, 683, 140, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Se deconnecter");
        Menu1.add(jLabel9);
        jLabel9.setBounds(33, 741, 128, 30);

        Menu2.setBackground(new java.awt.Color(255, 255, 255));

        Chercher.setBackground(new java.awt.Color(102, 102, 255));
        Chercher.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Chercher.setForeground(new java.awt.Color(255, 255, 255));
        Chercher.setText("Chercher");
        Chercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChercherMouseClicked(evt);
            }
        });
        Chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChercherActionPerformed(evt);
            }
        });

        filteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filteTXTActionPerformed(evt);
            }
        });
        filteTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filteTXTKeyReleased(evt);
            }
        });

        jTable2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID etudiant", "Nom", "Prenom", "Adresse_mail", "date_naissance","mot de passe"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        BEmprinter.setBackground(new java.awt.Color(102, 102, 255));
        BEmprinter.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BEmprinter.setForeground(new java.awt.Color(255, 255, 255));
        BEmprinter.setText("Ajouter");
        BEmprinter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEmprinterMouseClicked(evt);
            }
        });
        BEmprinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmprinterActionPerformed(evt);
            }
        });

        Supprimer.setBackground(new java.awt.Color(102, 102, 255));
        Supprimer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setText("Supprimer");
        Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerMouseClicked(evt);
            }
        });
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Actualiser.setBackground(new java.awt.Color(102, 102, 255));
        Actualiser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Actualiser.setForeground(new java.awt.Color(255, 255, 255));
        Actualiser.setText("Actualiser");
        Actualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualiserMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel11.setText("Consultation des Etudiants ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Welcome : ");

        welcome.setBackground(new java.awt.Color(102, 102, 255));
        welcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 102, 255));

        timelabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        timelabel1.setText("Time");

        datelabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        datelabel1.setText("Date");

        javax.swing.GroupLayout Menu2Layout = new javax.swing.GroupLayout(Menu2);
        Menu2.setLayout(Menu2Layout);
        Menu2Layout.setHorizontalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(BEmprinter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Supprimer)
                .addGap(198, 198, 198))
            .addGroup(Menu2Layout.createSequentialGroup()
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu2Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Menu2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Menu2Layout.createSequentialGroup()
                                .addComponent(timelabel1)
                                .addGap(128, 128, 128)
                                .addComponent(datelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Menu2Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(filteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Chercher)
                                .addGap(41, 41, 41)
                                .addComponent(Actualiser)))))
                .addGap(117, 127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        Menu2Layout.setVerticalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(timelabel1)
                        .addComponent(datelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chercher)
                    .addComponent(Actualiser))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEmprinter)
                    .addComponent(Supprimer))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(Menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChercherMouseClicked
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
            String query1 = "select etudiant.id,etudiant.NOM,etudiant.PRENOM,Etudiant.email,etudiant.date_naiss,etudiant.psw from etudiant;";
            pst = con.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String code = rs.getString("id");
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse_mail = rs.getString("email");
                String date_naissance = String.valueOf(rs.getDate("date_naiss"));
                String password=rs.getString("psw");

                String tbdata[] = {code, nom, prenom, adresse_mail,date_naissance, password};
                DefaultTableModel tb1model = (DefaultTableModel) jTable2.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(ex);
        }

        // version fausse
        /*
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotheque", "root", "");
            String query1 = "SELECT adherant.NOM,adherant.PRENOM,adherant.ADRESSE,COUNT(*) as nbexemplaires from emprunter INNER JOIN adherant on emprunter.CODEADHERANT=adherant.CODEADHERANT GROUP by adherant.CODEADHERANT;";
            pst = con.prepareStatement(query1); // soit ajouter des data ou lire des data 
            ResultSet rs = pst.executeQuery(); // lire data !!! 
            while (rs.next()) {
                
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse = rs.getString("adresse");
                String nbexemplaires = rs.getString("nbexemplaires");
                
                String tbdata[] = {nom, prenom, adresse, nbexemplaires};
                DefaultTableModel tb1model = (DefaultTableModel) jTable2.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(null, ex);
        }
         */

    }//GEN-LAST:event_ChercherMouseClicked

    private void filteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filteTXTActionPerformed

    private void filteTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filteTXTKeyReleased
        tb1model = (DefaultTableModel) jTable2.getModel();
        String search = filteTXT.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tb1model);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));

    }//GEN-LAST:event_filteTXTKeyReleased

    private void SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerMouseClicked
        int i = jTable2.getSelectedRow();
        DefaultTableModel tb1model = (DefaultTableModel) jTable2.getModel();
        isbn = tb1model.getValueAt(i, 0).toString();
        nom = tb1model.getValueAt(i, 1).toString();
        prenom = tb1model.getValueAt(i, 2).toString();
        adresse = tb1model.getValueAt(i, 3).toString();
        nbExemplaires = tb1model.getValueAt(i, 4).toString();

        if (nbExemplaires == "0") {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
                String query0 = "select id from etudiant where nom=?";
                pst = con.prepareStatement(query0);
                pst.setString(1, nom);
                ResultSet rs1 = pst.executeQuery();
                if (rs1.next()) {
                    this.id = rs1.getString("id");
                }
                JOptionPane.showMessageDialog(null, this.id);
                con.close();

                // supprimer adherant
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
                String query1 = "delete from etudiant where id =?";
                pst = con.prepareStatement(query1);
                pst.setString(1, this.id);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Etudiant supprimé");

                con.close();
            } catch (Exception ex) {
                JOptionPane.showInputDialog(ex);
            }

        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
                String query0 = "select id from etudiant where nom=?";
                pst = con.prepareStatement(query0);
                pst.setString(1, nom);
                ResultSet rs1 = pst.executeQuery();
                if (rs1.next()) {
                    this.code = rs1.getString("id");
                }
                JOptionPane.showMessageDialog(null, this.id);
                con.close();
   Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
                String query = "delete from emprunt where id_etud =?";
                pst = con.prepareStatement(query);
                pst.setString(1, this.id);
                pst.execute();

                JOptionPane.showMessageDialog(null, "exemplaire supprimé");

                con.close();
   Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
                String query1 = "delete from Etudiant where id =?";
                pst = con.prepareStatement(query1);
                pst.setString(1, this.id);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Etudiant supprimé");

                con.close();
            } catch (Exception ex) {
                JOptionPane.showInputDialog(ex);
            }

        }


        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
            String query0 = "select id from etudiant where nom=?";
            pst = con.prepareStatement(query0);
            pst.setString(1, nom);
            ResultSet rs1 = pst.executeQuery();
            if (rs1.next()) {
                this.id = rs1.getString("id");
            }
            JOptionPane.showMessageDialog(null, this.id);
            
        } catch (Exception ex) {
            JOptionPane.showInputDialog(ex);
        }

        //auteur = tb1model.getValueAt(i, 4).toString();
        
        try {
 Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
            String query = "delete from emprunt where id_etud =?";
            pst = con.prepareStatement(query);
            pst.setString(1, this.id);
            pst.execute();

            JOptionPane.showMessageDialog(null, "exemplaire supprimé");

            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(null, ex);
        }
        try {
Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
            String query1 = "delete from etudiant where id =?";
            pst = con.prepareStatement(query1);
            pst.setString(1, this.id);
            pst.execute();

                JOptionPane.showMessageDialog(null, "Etudiant supprimé");

            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(null, ex);
        }


    }//GEN-LAST:event_SupprimerMouseClicked

    private void ActualiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiserMouseClicked

        DefaultTableModel tb1model = (DefaultTableModel) jTable2.getModel();
        tb1model.setNumRows(0);

        try {
Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_biblio", "root", "");
            String query1 = "select Etudiant.id,etudiant.NOM,etudiant.PRENOM,etudiant.email,etudiant.date_naiss,etudiant.psw from etudiant;";
            pst = con.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String code = rs.getString("id");
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse_mail = rs.getString("email");
                String date_naissance =String.valueOf(rs.getDate("date_naiss"));
                String password=rs.getString("psw");
                String tbdata[] = {code,nom, prenom, adresse_mail, date_naissance,password};
                tb1model = (DefaultTableModel) jTable2.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(ex);
        }

        // version fausse
        /*
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotheque", "root", "");
            String query1 = "SELECT adherant.NOM,adherant.PRENOM,adherant.ADRESSE,COUNT(*) as nbexemplaires from emprunter INNER JOIN adherant on emprunter.CODEADHERANT=adherant.CODEADHERANT GROUP by adherant.CODEADHERANT;";
            pst = con.prepareStatement(query1); // soit ajouter des data ou lire des data 
            ResultSet rs = pst.executeQuery(); // lire data !!! 
            while (rs.next()) {
                
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse = rs.getString("adresse");
                String nbexemplaires = rs.getString("nbexemplaires");
                
                String tbdata[] = {nom, prenom, adresse, nbexemplaires};
                tb1model = (DefaultTableModel) jTable2.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotheque", "root", "");
            String query1 = "SELECT adherant.NOM,adherant.PRENOM,adherant.ADRESSE,adherant.nbexemplaire from adherant where adherant.nom=?";
            pst = con.prepareStatement(query1); // soit ajouter des data ou lire des data 
            pst.setString(1, Adherant.TNom.getText());
            ResultSet rs = pst.executeQuery(); // lire data !!! 
            while (rs.next()) {
                
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse = rs.getString("adresse");
                String nbexemplaires = rs.getString("nbexemplaire");
                
                String tbdata[] = {nom, prenom, adresse, nbexemplaires};
                tb1model = (DefaultTableModel) jTable2.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
            //JOptionPane.showInputDialog(null, ex);
        }
         */

    }//GEN-LAST:event_ActualiserMouseClicked

    private void BEmprinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmprinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BEmprinterActionPerformed

    private void BEmprinterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEmprinterMouseClicked
        Etudiant m = new Etudiant();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_BEmprinterMouseClicked

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupprimerActionPerformed

    private void pretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretMouseClicked
        MenuPret m = new MenuPret();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pretMouseClicked

    private void MenuLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLMouseClicked
        MenuLivres m = new MenuLivres();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuLMouseClicked

    private void MenuAdhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdhMouseClicked
        MenuEtudiant m = new MenuEtudiant();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuAdhMouseClicked

    private void LivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LivreMouseClicked
        
    }//GEN-LAST:event_LivreMouseClicked

    private void ChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChercherActionPerformed

    private void menuppretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuppretMouseClicked
       MenuPret m = new MenuPret();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_menuppretMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Statistic m = new Statistic();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       Login m = new Login();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualiser;
    private javax.swing.JLabel Adherant;
    private javax.swing.JButton BEmprinter;
    private javax.swing.JButton Chercher;
    private javax.swing.JLabel Livre;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JLabel MenuAdh;
    private javax.swing.JLabel MenuL;
    private javax.swing.JButton Supprimer;
    private javax.swing.JLabel datelabel1;
    private javax.swing.JTextField filteTXT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel menuppret;
    private javax.swing.JLabel pret;
    private javax.swing.JLabel timelabel1;
    public static javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

}
