/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbibilio.MenuPret;

import Statistics.Statistic;
import gbibilio.MenuAdherant.*;
import gbibilio.MenuLivres.MenuLivres;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import login.Login;

/**
 *
 * @author mehdi
 */
public class CLivres extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    DefaultTableModel tb1model;

    String isbn;
    String titre;
    String edition;
    String nbpages;
    String nbexemplaires;
    String code;

    /**
     * Creates new form Menu
     */
    public CLivres() {
        initComponents();
        showdate();
        showTime();
        this.setLocationRelativeTo(null);

    }

    void showdate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyy");
        datelabel1.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() { // pendant 0 secande fait moi une action qui s'appele 'ActionListener'
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timelabel1.setText(s.format(d));

            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu3 = new javax.swing.JPanel();
        Livre1 = new javax.swing.JLabel();
        MenuLi = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        pret = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        adher = new javax.swing.JLabel();
        Menuadh = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        menupret = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        Chercher = new javax.swing.JButton();
        filteTXT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        EmprinterGoto = new javax.swing.JButton();
        Actualiser = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        timelabel1 = new javax.swing.JLabel();
        datelabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        /*date1 = new com.toedter.calendar.JDateChooser();*/
        /*date2 = new com.toedter.calendar.JDateChooser();*/

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu3.setBackground(new java.awt.Color(102, 102, 255));
        Menu3.setLayout(null);

        Livre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livres (1).png"))); // NOI18N
        Livre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Livre1MouseClicked(evt);
            }
        });
        Menu3.add(Livre1);
        Livre1.setBounds(40, 20, 130, 120);

        MenuLi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuLi.setForeground(new java.awt.Color(255, 255, 255));
        MenuLi.setText("Gestion Livre");
        MenuLi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLiMouseClicked(evt);
            }
        });
        Menu3.add(MenuLi);
        MenuLi.setBounds(40, 150, 128, 30);
        Menu3.add(jSeparator5);
        jSeparator5.setBounds(0, 180, 190, 10);

        pret.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knowledge (1).png"))); // NOI18N
        pret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pretMouseClicked(evt);
            }
        });
        Menu3.add(pret);
        pret.setBounds(28, 366, 130, 110);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestion Statictics");
        Menu3.add(jLabel4);
        jLabel4.setBounds(30, 630, 128, 30);
        Menu3.add(jSeparator2);
        jSeparator2.setBounds(0, 350, 190, 10);

        adher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student (1).png"))); // NOI18N
        Menu3.add(adher);
        adher.setBounds(40, 200, 140, 110);

        Menuadh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menuadh.setForeground(new java.awt.Color(255, 255, 255));
        Menuadh.setText("Gestion Adherant");
        Menuadh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuadhMouseClicked(evt);
            }
        });
        Menu3.add(Menuadh);
        Menuadh.setBounds(30, 310, 128, 30);
        Menu3.add(jSeparator3);
        jSeparator3.setBounds(0, 500, 190, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph-bar (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        Menu3.add(jLabel7);
        jLabel7.setBounds(30, 520, 140, 110);

        menupret.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menupret.setForeground(new java.awt.Color(255, 255, 255));
        menupret.setText("Gestion des prêts");
        Menu3.add(menupret);
        menupret.setBounds(30, 470, 128, 30);
        Menu3.add(jSeparator4);
        jSeparator4.setBounds(0, 660, 190, 10);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        Menu3.add(jLabel10);
        jLabel10.setBounds(21, 663, 140, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Se deconnecter");
        Menu3.add(jLabel9);
        jLabel9.setBounds(30, 720, 128, 30);

        Menu2.setBackground(new java.awt.Color(255, 255, 255));
        Menu2.setLayout(null);

        Chercher.setBackground(new java.awt.Color(102, 102, 255));
        Chercher.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Chercher.setForeground(new java.awt.Color(255, 255, 255));
        Chercher.setText("Chercher");
        Chercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChercherMouseClicked(evt);
            }
        });
        Chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChercherActionPerformed(evt);
            }
        });
        Menu2.add(Chercher);
        Chercher.setBounds(638, 168, 105, 29);

        filteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filteTXTActionPerformed(evt);
            }
        });
        filteTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filteTXTKeyReleased(evt);
            }
        });
        Menu2.add(filteTXT);
        filteTXT.setBounds(366, 166, 237, 35);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titre", "Edition", "NbPages", "NbExemplaires"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        Menu2.add(jScrollPane2);
        jScrollPane2.setBounds(131, 233, 860, 402);

        EmprinterGoto.setBackground(new java.awt.Color(102, 102, 255));
        EmprinterGoto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmprinterGoto.setForeground(new java.awt.Color(255, 255, 255));
        EmprinterGoto.setText("Préter");
        EmprinterGoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmprinterGotoMouseClicked(evt);
            }
        });
        EmprinterGoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmprinterGotoActionPerformed(evt);
            }
        });
        Menu2.add(EmprinterGoto);
        EmprinterGoto.setBounds(680, 690, 85, 29);

        Actualiser.setBackground(new java.awt.Color(102, 102, 255));
        Actualiser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Actualiser.setForeground(new java.awt.Color(255, 255, 255));
        Actualiser.setText("Actualiser");
        Actualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualiserMouseClicked(evt);
            }
        });
        Menu2.add(Actualiser);
        Actualiser.setBounds(784, 168, 115, 29);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel11.setText("Consultation des Livres  ");
        Menu2.add(jLabel11);
        jLabel11.setBounds(293, 76, 643, 51);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Welcome : ");
        Menu2.add(jLabel12);
        jLabel12.setBounds(701, 30, 70, 17);

        welcome.setBackground(new java.awt.Color(102, 102, 255));
        welcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 102, 255));
        Menu2.add(welcome);
        welcome.setBounds(780, 10, 130, 42);

        timelabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        timelabel1.setText("Time");
        Menu2.add(timelabel1);
        timelabel1.setBounds(34, 29, 33, 19);

        datelabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        datelabel1.setText("Date");
        Menu2.add(datelabel1);
        datelabel1.setBounds(195, 13, 120, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Date d'emprinte : ");
        Menu2.add(jLabel1);
        jLabel1.setBounds(181, 666, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date de retour : ");
        Menu2.add(jLabel2);
        jLabel2.setBounds(180, 720, 120, 17);
        /*Menu2.add(date1);
        date1.setBounds(320, 710, 170, 30);
        Menu2.add(date2);
        date2.setBounds(320, 670, 170, 30);*/

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChercherMouseClicked
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");
            String query1 = "select livre.ISBN,livre.TITRE,livre.EDITION,livre.NBPAGES ,COUNT(*) as nbExemplaires from livre inner join exemplaire on exemplaire.ISBN=livre.ISBN group by livre.ISBN;";
            pst = con.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                isbn = rs.getString("ISBN");
                titre = rs.getString("TITRE");
                edition = rs.getString("EDITION");
                nbpages = rs.getString("NBPAGES");
                nbexemplaires = rs.getString("nbExemplaires");

                String tbdata[] = {isbn, titre, edition, nbpages, nbexemplaires};
                DefaultTableModel tb1model = (DefaultTableModel) jTable2.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(ex);
        }

    }//GEN-LAST:event_ChercherMouseClicked

    private void filteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filteTXTActionPerformed

    private void filteTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filteTXTKeyReleased
        tb1model = (DefaultTableModel) jTable2.getModel();
        String search = filteTXT.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tb1model);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));

    }//GEN-LAST:event_filteTXTKeyReleased

    private void EmprinterGotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmprinterGotoMouseClicked
        
        int i = jTable2.getSelectedRow();
        tb1model = (DefaultTableModel) jTable2.getModel();
        isbn = tb1model.getValueAt(i, 0).toString();
        String nb = tb1model.getValueAt(i, 4).toString();
        if(nb.contains("0")){
            JOptionPane.showMessageDialog(null, "Impossible d'enprinter car le livre n'as pas d'exmplaire");
        }else{
            CExem m = new CExem();
            m.setVisible(true);
            m.setLocationRelativeTo(null);
            
        }
       


    }//GEN-LAST:event_EmprinterGotoMouseClicked

    private void ActualiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiserMouseClicked


    }//GEN-LAST:event_ActualiserMouseClicked

    private void EmprinterGotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmprinterGotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmprinterGotoActionPerformed

    private void ChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChercherActionPerformed

    private void MenuadhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuadhMouseClicked
        MenuEtudiant m = new MenuEtudiant();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuadhMouseClicked

    private void pretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretMouseClicked
        MenuPret m = new MenuPret();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pretMouseClicked

    private void MenuLiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLiMouseClicked
        MenuLivres m = new MenuLivres();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuLiMouseClicked

    private void Livre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Livre1MouseClicked

    }//GEN-LAST:event_Livre1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Statistic m = new Statistic();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       Login m = new Login();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLivres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLivres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLivres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLivres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLivres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualiser;
    private javax.swing.JButton Chercher;
    private javax.swing.JButton EmprinterGoto;
    private javax.swing.JLabel Livre1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JPanel Menu3;
    private javax.swing.JLabel MenuLi;
    private javax.swing.JLabel Menuadh;
    private javax.swing.JLabel adher;
/*    public static com.toedter.calendar.JDateChooser date1;
    public static com.toedter.calendar.JDateChooser date2;*/
    private javax.swing.JLabel datelabel1;
    private javax.swing.JTextField filteTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public static javax.swing.JTable jTable2;
    private javax.swing.JLabel menupret;
    private javax.swing.JLabel pret;
    private javax.swing.JLabel timelabel1;
    public static javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

}
