/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbibilio.MenuPret;

import Statistics.Statistic;
import gbibilio.MenuAdherant.*;
import gbibilio.MenuLivres.MenuLivres;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import login.Login;

/**
 *
 * @author mehdi
 */
public class MenuPret extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    DefaultTableModel tb1model;
    String auteur;
    String nom;
    String prenom;
    String adresse;
    String nbExemplaires;
    String id;
    String code;
    String isbn;

    /**
     * Creates new form Menu
     */
    public MenuPret() {
        initComponents();
        showdate();
        showTime();
        this.setLocationRelativeTo(null);

    }

    void showdate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyy");
        datelabel1.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() { // pendant 0 secande fait moi une action qui s'appele 'ActionListener'
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timelabel1.setText(s.format(d));

            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu1 = new javax.swing.JPanel();
        MenuLivre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Livre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Adherant = new javax.swing.JLabel();
        MenuAdherant = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pre = new javax.swing.JLabel();
        menupre = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        Chercher = new javax.swing.JButton();
        filteTXT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        BEmprinter = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Actualiser = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        timelabel1 = new javax.swing.JLabel();
        datelabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu1.setBackground(new java.awt.Color(102, 102, 255));
        Menu1.setLayout(null);

        MenuLivre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuLivre.setForeground(new java.awt.Color(255, 255, 255));
        MenuLivre.setText("Gestion Livre");
        MenuLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLivreMouseClicked(evt);
            }
        });
        Menu1.add(MenuLivre);
        MenuLivre.setBounds(40, 130, 100, 30);
        Menu1.add(jSeparator1);
        jSeparator1.setBounds(0, 170, 190, 10);

        Livre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livres (1).png"))); // NOI18N
        Livre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LivreMouseClicked(evt);
            }
        });
        Menu1.add(Livre);
        Livre.setBounds(40, 20, 140, 106);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestion Statictics");
        Menu1.add(jLabel4);
        jLabel4.setBounds(30, 620, 128, 30);
        Menu1.add(jSeparator2);
        jSeparator2.setBounds(0, 340, 190, 10);

        Adherant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student (1).png"))); // NOI18N
        Menu1.add(Adherant);
        Adherant.setBounds(40, 190, 140, 110);

        MenuAdherant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuAdherant.setForeground(new java.awt.Color(255, 255, 255));
        MenuAdherant.setText("Gestion Adherant");
        MenuAdherant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdherantMouseClicked(evt);
            }
        });
        Menu1.add(MenuAdherant);
        MenuAdherant.setBounds(30, 300, 128, 30);
        Menu1.add(jSeparator3);
        jSeparator3.setBounds(0, 490, 190, 10);

        pre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knowledge (1).png"))); // NOI18N
        pre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preMouseClicked(evt);
            }
        });
        Menu1.add(pre);
        pre.setBounds(30, 360, 130, 100);

        menupre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menupre.setForeground(new java.awt.Color(255, 255, 255));
        menupre.setText("Gestion des prêts");
        Menu1.add(menupre);
        menupre.setBounds(30, 460, 128, 30);
        Menu1.add(jSeparator4);
        jSeparator4.setBounds(0, 650, 190, 10);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph-bar (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        Menu1.add(jLabel10);
        jLabel10.setBounds(40, 500, 110, 120);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Se deconnecter");
        Menu1.add(jLabel9);
        jLabel9.setBounds(30, 710, 128, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Menu1.add(jLabel1);
        jLabel1.setBounds(20, 660, 150, 50);

        Menu2.setBackground(new java.awt.Color(255, 255, 255));

        Chercher.setBackground(new java.awt.Color(102, 102, 255));
        Chercher.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Chercher.setForeground(new java.awt.Color(255, 255, 255));
        Chercher.setText("Chercher");
        Chercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChercherMouseClicked(evt);
            }
        });
        Chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChercherActionPerformed(evt);
            }
        });

        filteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filteTXTActionPerformed(evt);
            }
        });
        filteTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filteTXTKeyReleased(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Adherant", "Nom", "Prenom", "Adresse", "NbExemplaires"
            }
        ));
        jScrollPane2.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
        }

        BEmprinter.setBackground(new java.awt.Color(102, 102, 255));
        BEmprinter.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BEmprinter.setForeground(new java.awt.Color(255, 255, 255));
        BEmprinter.setText("Préter");
        BEmprinter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEmprinterMouseClicked(evt);
            }
        });
        BEmprinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmprinterActionPerformed(evt);
            }
        });

        Supprimer.setBackground(new java.awt.Color(102, 102, 255));
        Supprimer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setText("Récupérer");
        Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerMouseClicked(evt);
            }
        });
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Actualiser.setBackground(new java.awt.Color(102, 102, 255));
        Actualiser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Actualiser.setForeground(new java.awt.Color(255, 255, 255));
        Actualiser.setText("Actualiser");
        Actualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualiserMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel11.setText("Gerer les préts  ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Welcome : ");

        welcome.setBackground(new java.awt.Color(102, 102, 255));
        welcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 102, 255));

        timelabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        timelabel1.setText("Time");

        datelabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        datelabel1.setText("Date");

        javax.swing.GroupLayout Menu2Layout = new javax.swing.GroupLayout(Menu2);
        Menu2.setLayout(Menu2Layout);
        Menu2Layout.setHorizontalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(BEmprinter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Supprimer)
                .addGap(161, 161, 161))
            .addGroup(Menu2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu2Layout.createSequentialGroup()
                        .addComponent(timelabel1)
                        .addGap(128, 128, 128)
                        .addComponent(datelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Menu2Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Menu2Layout.createSequentialGroup()
                                .addComponent(filteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Chercher)
                                .addGap(41, 41, 41)
                                .addComponent(Actualiser)))))
                .addGap(71, 71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
        );
        Menu2Layout.setVerticalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(timelabel1)
                        .addComponent(datelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chercher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Supprimer)
                    .addComponent(BEmprinter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChercherMouseClicked
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");
            String query1 = "select adherant.codeadherant,adherant.NOM,adherant.PRENOM,adherant.ADRESSE,adherant.nbexemplaires from adherant;";
            pst = con.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String code = rs.getString("codeadherant");
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse = rs.getString("adresse");
                String nbexemplaires = rs.getString("nbexemplaires");

                String tbdata[] = {code, nom, prenom, adresse, nbexemplaires};
                DefaultTableModel tb1model = (DefaultTableModel) jTable3.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(ex);
        }

    }//GEN-LAST:event_ChercherMouseClicked

    private void filteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filteTXTActionPerformed

    private void filteTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filteTXTKeyReleased
        tb1model = (DefaultTableModel) jTable3.getModel();
        String search = filteTXT.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tb1model);
        jTable3.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));

    }//GEN-LAST:event_filteTXTKeyReleased

    private void SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerMouseClicked
        int i = jTable3.getSelectedRow();
        DefaultTableModel tb1model = (DefaultTableModel) jTable3.getModel();
        isbn = tb1model.getValueAt(i, 0).toString();
        nom = tb1model.getValueAt(i, 1).toString();
        prenom = tb1model.getValueAt(i, 2).toString();
        adresse = tb1model.getValueAt(i, 3).toString();
        nbExemplaires = tb1model.getValueAt(i, 4).toString();
        
        

        if (nbExemplaires.contains("0")) {

            JOptionPane.showMessageDialog(null, "Adherant n'a aucun exemplaire à returner");

        } else {
            try {

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");
                String query0 = "select codeadherant from adherant where nom=?";
                pst = con.prepareStatement(query0);
                pst.setString(1, nom);
                ResultSet rs1 = pst.executeQuery();
                if (rs1.next()) {
                    this.code = rs1.getString("codeadherant");
                }
                //JOptionPane.showMessageDialog(null, this.code);
                con.close();

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");
                String query = "delete from emprunter where codeadherant =?";
                pst = con.prepareStatement(query);
                pst.setString(1, this.code);
                pst.execute();

                JOptionPane.showMessageDialog(null, "exemplaire bien retourné");

                con.close();
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");
                String query1 = "UPDATE adherant set adherant.nbexemplaires=0 WHERE adherant.NOM=?;";
                pst = con.prepareStatement(query1);
                pst.setString(1, this.nom);
                pst.execute();

                JOptionPane.showMessageDialog(null, "sycno done");

                con.close();
            } catch (Exception ex) {
                JOptionPane.showInputDialog(ex);
            }

        }
        


    }//GEN-LAST:event_SupprimerMouseClicked

    private void ActualiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiserMouseClicked

        DefaultTableModel tb1model = (DefaultTableModel) jTable3.getModel();
        tb1model.setNumRows(0);

        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gbiblio", "root", "");
            String query1 = "select adherant.codeadherant,adherant.NOM,adherant.PRENOM,adherant.ADRESSE,adherant.nbexemplaires from adherant;";
            pst = con.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String id = rs.getString("codeadherant");
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse = rs.getString("adresse");
                String nbexemplaires = rs.getString("nbexemplaires");

                String tbdata[] = {id, nom, prenom, adresse, nbexemplaires};
                tb1model = (DefaultTableModel) jTable3.getModel();
                tb1model.addRow(tbdata);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showInputDialog(ex);
        }


    }//GEN-LAST:event_ActualiserMouseClicked

    private void BEmprinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmprinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BEmprinterActionPerformed

    private void BEmprinterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEmprinterMouseClicked
        CLivres m = new CLivres();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BEmprinterMouseClicked

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupprimerActionPerformed

    private void MenuLivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLivreMouseClicked
        MenuLivres m = new MenuLivres();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuLivreMouseClicked

    private void MenuAdherantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdherantMouseClicked
        MenuEtudiant m = new MenuEtudiant();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuAdherantMouseClicked

    private void LivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LivreMouseClicked

    }//GEN-LAST:event_LivreMouseClicked

    private void ChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChercherActionPerformed

    private void preMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preMouseClicked
        MenuPret m = new MenuPret();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_preMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Statistic m = new Statistic();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Login m = new Login();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPret().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualiser;
    private javax.swing.JLabel Adherant;
    private javax.swing.JButton BEmprinter;
    private javax.swing.JButton Chercher;
    private javax.swing.JLabel Livre;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JLabel MenuAdherant;
    private javax.swing.JLabel MenuLivre;
    private javax.swing.JButton Supprimer;
    private javax.swing.JLabel datelabel1;
    private javax.swing.JTextField filteTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public static javax.swing.JTable jTable3;
    private javax.swing.JLabel menupre;
    private javax.swing.JLabel pre;
    private javax.swing.JLabel timelabel1;
    public static javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

}
